### PR TITLE
Fix Conflicts

### PR DESCRIPTION
**Pull request by ranocha**
I've fixed merge conflicts and re-added some additions that have been removed.

### CODE REVIEW

**Comment by philipheinisch** [comment]
Seems largely ok, but why is the first letter for intel and nvidia not capitalized like all the other directory or variable names? Is there a reason for the missing support for temperature output on dual socket systems or just the missing hardware to test on? In this case, I can implement and test it.

**Comment by ranocha** [comment]
> Why is the first letter for intel and nvidia not capitalized like all the other directory or variable names?

I thought we decided to use directory names in the same way as command line arguments, cf. https://github.com/IANW-Projects/toolkitICL/pull/18#issuecomment-469826865.  We could also use capitalised names, but then we had to remember whether we want to have, e.g. `Amd` or `AMD`.

By the way, should we use `/Housekeeping/AMD` or `/Housekeeping/amd`?

**Comment by ranocha** [comment]
> Is there a reason for the missing support for temperature output on dual socket systems or just the missing hardware to test on? In this case, I can implement and test it.

I just didn't have the hardware. It would be great if you could test and implement it.

**Comment by philipheinisch** [comment]
> > Why is the first letter for intel and nvidia not capitalized like all the other directory or variable names?
> 
> I thought we decided to use directory names in the same way as command line arguments, cf. [IANW-Projects#18 (comment)](https://github.com/IANW-Projects/toolkitICL/pull/18#issuecomment-469826865). We could also use capitalised names, but then we had to remember whether we want to have, e.g. `Amd` or `AMD`.
> 
> By the way, should we use `/Housekeeping/AMD` or `/Housekeeping/amd`?

I see. But now it is inconsistent with the rest, which might be counterintuitive for users.

**Comment by ranocha** [comment]
I really dislike `Amd`.

**Comment by philipheinisch** [comment]
OK, so `Amd` is out! 
Could you have a look at the dual socket temperature implementation and see if you like it this way?

**Comment by ranocha** [comment]
Besides some indentation issues (tabs...) this looks good to me.

**Comment by ranocha** [comment]
Shall we discuss the naming scheme via VoIP?

**Comment by ranocha** [comment]
Naming schemes of the output file:
- All lower case and underscores
- Directory `architecture`: Host_OS, OpenCL_Device, OpenCL_Platform, OpenCL_Version
- `settings`: Global_Range, Local_Range, Range_Start, Kernel_Settings
- `housekeeping`: additionally Data_LoadTime, Data_StoreTime, Kernel_ExecStart, Kernel_ExecTime, Total_ExecTime
- `execution_time` etc.

**Pull request merged**
